export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const POST_TODO_REQUEST = 'POST_TODO_REQUEST ';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS ';
export const POST_TODO_FAILURE = 'POST_TODO_FAILURE ';


export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE' ;


export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST '
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS '
export const TOGGLE_TODO_FAILURE= 'TOGGLE_TODO_FAILURE'